/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.controladorEnunciado6;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Acceso a datos
 */
public class Enunciado6 extends javax.swing.JFrame {
     /**
     * Creates new form Enunciado5
     */
    public Enunciado6() {
        initComponents();
        controladorEnunciado6.iniciaSession();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmpleados = new javax.swing.JLabel();
        lblDepartamentos = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblComentario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaEmpleados = new javax.swing.JTextArea();
        lblNumDep = new javax.swing.JLabel();
        txtNumDep = new javax.swing.JTextField();
        btnQuerydos = new javax.swing.JButton();
        lblnombreDepartamento = new javax.swing.JLabel();
        lblNumeroEmpleados = new javax.swing.JLabel();
        lblNumeroDepartamentos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaDepartamento = new javax.swing.JTextArea();
        btnQueryDatosPrimitivos = new javax.swing.JButton();
        btnQueryList = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        lblEmpleados.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblEmpleados.setText("Empleados");

        lblDepartamentos.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblDepartamentos.setText("Departamentos");
        lblDepartamentos.setToolTipText("");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblApellido.setText("Apellido");

        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoKeyReleased(evt);
            }
        });

        lblComentario.setText("La consulta se visualiza a medida que se escribe el nombre");

        txtAreaEmpleados.setColumns(20);
        txtAreaEmpleados.setRows(5);
        jScrollPane1.setViewportView(txtAreaEmpleados);

        lblNumDep.setText("Nº Departamento");

        btnQuerydos.setText("Empleados por departamento");
        btnQuerydos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuerydosActionPerformed(evt);
            }
        });

        lblnombreDepartamento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblnombreDepartamento.setText("Departamento");

        lblNumeroEmpleados.setText("Nº Empleados");

        lblNumeroDepartamentos.setText("Nº de Departamentos");

        txtAreaDepartamento.setColumns(20);
        txtAreaDepartamento.setRows(5);
        jScrollPane2.setViewportView(txtAreaDepartamento);

        btnQueryDatosPrimitivos.setText("Query Datos Primitivos");
        btnQueryDatosPrimitivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueryDatosPrimitivosActionPerformed(evt);
            }
        });

        btnQueryList.setText("Query List");
        btnQueryList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueryListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(lblEmpleados))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDepartamentos)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnQueryDatosPrimitivos)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQueryList))
                        .addComponent(lblnombreDepartamento)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblNumDep)
                            .addGap(31, 31, 31)
                            .addComponent(txtNumDep, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(btnQuerydos))
                        .addComponent(lblNumeroEmpleados)
                        .addComponent(lblNumeroDepartamentos))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblEmpleados)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblComentario)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblDepartamentos)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumDep)
                    .addComponent(txtNumDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuerydos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblnombreDepartamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNumeroEmpleados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNumeroDepartamentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQueryDatosPrimitivos)
                    .addComponent(btnQueryList))
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        controladorEnunciado6.cerrarSession();
    }//GEN-LAST:event_formWindowClosed

    private void txtApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyReleased
        //Empleados por apellido
        controladorEnunciado6.queryuno();
    }//GEN-LAST:event_txtApellidoKeyReleased

    private void btnQuerydosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuerydosActionPerformed
        // Empleados por numero de departamento
        controladorEnunciado6.querydos();
    }//GEN-LAST:event_btnQuerydosActionPerformed

    private void btnQueryDatosPrimitivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueryDatosPrimitivosActionPerformed
        //En esta consulta vamos a recoger datos y no directamente objetos de la clase
        controladorEnunciado6.querytres();
    }//GEN-LAST:event_btnQueryDatosPrimitivosActionPerformed

    private void btnQueryListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueryListActionPerformed
        controladorEnunciado6.querycuatro();
    }//GEN-LAST:event_btnQueryListActionPerformed

    public JTextField getTxtApellido() {
        return txtApellido;
    }

    public JTextArea getTxtAreaDepartamento() {
        return txtAreaDepartamento;
    }

    public JTextArea getTxtAreaEmpleados() {
        return txtAreaEmpleados;
    }

    public JTextField getTxtNumDep() {
        return txtNumDep;
    }

    public JLabel getLblNumeroDepartamentos() {
        return lblNumeroDepartamentos;
    }

    public JLabel getLblNumeroEmpleados() {
        return lblNumeroEmpleados;
    }

    public JLabel getLblnombreDepartamento() {
        return lblnombreDepartamento;
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQueryDatosPrimitivos;
    private javax.swing.JButton btnQueryList;
    private javax.swing.JButton btnQuerydos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblComentario;
    private javax.swing.JLabel lblDepartamentos;
    private javax.swing.JLabel lblEmpleados;
    private javax.swing.JLabel lblNumDep;
    private javax.swing.JLabel lblNumeroDepartamentos;
    private javax.swing.JLabel lblNumeroEmpleados;
    private javax.swing.JLabel lblnombreDepartamento;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextArea txtAreaDepartamento;
    private javax.swing.JTextArea txtAreaEmpleados;
    private javax.swing.JTextField txtNumDep;
    // End of variables declaration//GEN-END:variables
}
